import {
  Axe,
  Backpack,
  Beer,
  Circle,
  Coins,
  Cross,
  Crown,
  EyeOff,
  Feather,
  FlaskConical,
  Footprints,
  Gem,
  Hammer,
  Heart,
  Home,
  type LucideIcon,
  Map,
  Mountain,
  Scroll,
  Shield,
  Shirt,
  Skull,
  Sparkles,
  Sword,
  Swords,
  Target,
  User,
  Wand,
  Zap,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  axe: Axe,
  backpack: Backpack,
  beer: Beer,
  bow: Target,
  circle: Circle,
  coins: Coins,
  cross: Cross,
  crown: Crown,
  'eye-off': EyeOff,
  feather: Feather,
  potion: FlaskConical,
  'potion-red': FlaskConical,
  'potion-blue': FlaskConical,
  elixir: FlaskConical,
  boots: Footprints,
  crystal: Gem,
  hammer: Hammer,
  heart: Heart,
  home: Home,
  map: Map,
  ore: Mountain,
  scroll: Scroll,
  shield: Shield,
  armor: Shield,
  helmet: Shield,
  gloves: Shield,
  shirt: Shirt,
  robe: Shirt,
  cloak: Shirt,
  skull: Skull,
  sparkles: Sparkles,
  sword: Sword,
  dagger: Sword,
  swords: Swords,
  target: Target,
  crossbow: Target,
  user: User,
  wand: Wand,
  staff: Wand,
  zap: Zap,
}

export function getIconFromName(name: string | null | undefined) {
  if (!name) return Circle
  const normalizedName = name.toLowerCase()
  return iconMap[normalizedName] || Circle
}
