import type { LucideIcon } from 'lucide-react'
import {
  Axe,
  Beer,
  Book,
  Brain,
  Briefcase,
  Circle,
  Cross,
  Crown,
  Dna,
  Droplet,
  Eye,
  Flame,
  Footprints,
  Ghost,
  Hammer,
  Heart,
  Hexagon,
  Home,
  Key,
  Map,
  Mountain,
  Scroll,
  Shield,
  Shirt,
  Skull,
  Sparkles,
  Star,
  Store,
  Sword,
  Swords,
  Target,
  Tent,
  Trees,
  User,
  Users,
  Wand,
  Wind,
  Zap,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  axe: Axe,
  beer: Beer,
  book: Book,
  bow: Target,
  brain: Brain,
  briefcase: Briefcase,
  circle: Circle,
  cross: Cross,
  crown: Crown,
  dna: Dna,
  droplet: Droplet,
  eye: Eye,
  flame: Flame,
  footprints: Footprints,
  ghost: Ghost,
  hammer: Hammer,
  heart: Heart,
  hexagon: Hexagon,
  home: Home,
  key: Key,
  map: Map,
  mountain: Mountain,
  scroll: Scroll,
  shield: Shield,
  shirt: Shirt,
  skull: Skull,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sword: Sword,
  swords: Swords,
  target: Target,
  tent: Tent,
  trees: Trees,
  user: User,
  users: Users,
  wand: Wand,
  wind: Wind,
  zap: Zap,
}

export function getIconFromName(name: string | null | undefined) {
  if (!name) return Circle
  const normalizedName = name.toLowerCase()
  return iconMap[normalizedName] || Circle
}
