import '~/styles/globals.css'

import { getServerAuthSession } from '~/server/auth'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import ThemeRegistry from '~/styles/theme'
import { TRPCReactProvider } from '~/trpc/react'
import NextAuthProvider from '~/ctx/auth-provider'

import _Init from './_components/_init'
import Link from 'next/link'
import { Main } from '~/styles/common'
import MenuLeft from './_components/menu-left'
import MenuRight from './_components/menu-right'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Land of Machala App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerAuthSession()

  return (
    <html lang='en'>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <_Init />

          <NextAuthProvider>
            <ThemeRegistry options={{ key: 'mui' }}>
              {!session && (
                <Link
                  href={'/api/auth/signin'}
                  className='rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20'
                >
                  {'Sign in'}
                </Link>
              )}

              {session && (
                <>
                  <header></header>
                  <Main>
                    <MenuLeft />
                    {children}
                    <MenuRight />
                  </Main>
                  <footer></footer>
                </>
              )}
            </ThemeRegistry>
          </NextAuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
