import '~/styles/globals.css'
import { Inter } from 'next/font/google'
import { cn } from '~/lib/utils'
import { getServerAuthSession } from '~/server/auth'
import { cookies } from 'next/headers'

import NextAuthProvider from '~/ctx/auth-provider'
import { TRPCReactProvider } from '~/trpc/react'
import { ThemeProvider } from '~/components/theme-provider'

import _Init from '../components/_init'
import Link from 'next/link'
import { Main } from '~/styles/common'
import MenuLeft from '../components/ui/menu-left'
import MenuRight from '../components/ui/menu-right'
import Sidebar from '../components/ui/sidebar'
import GlobalStyles from '~/styles/GlobalStyles'

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Land of Machala App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerAuthSession()

  return (
    <html lang='en'>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <GlobalStyles />
          <_Init />

          <NextAuthProvider>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
              {!session && (
                <Link
                  href={'/api/auth/signin'}
                  className='rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20'
                >
                  {'Sign in'}
                </Link>
              )}

              {session && (
                <>
                  <header></header>
                  <Main className='h-screen w-screen bg-white dark:bg-slate-900'>
                    <Sidebar $direction='right'>
                      <MenuLeft />
                    </Sidebar>
                    {/* <section className='p-5'>{children}</section> */}
                    {/* <Sidebar $direction='right'>
                      <MenuRight />
                    </Sidebar> */}
                  </Main>
                  <footer></footer>
                </>
              )}
            </ThemeProvider>
          </NextAuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
