export const QUERY_KEY = {
  ARMORY: 'armory-key',
  BANK: 'bank-key',
  BANK_ACCOUNT: 'bank-account-key',
  CLASS: 'class-key',
  GAME_INFO: 'game-info-key',
  HOSPITAL: 'hospital-key',
  INVENTORY: 'inventory-key',
  LANDING: 'landing-key',
  CREATE: 'create-key',
  PLAYER: 'player-key',
  QUEST_ASSIGNED: 'quest-assigned-key',
  RACE: 'race-key',
  STATS: 'stats-key',
  WEARABLE: 'wearable-key',
}
